repos:
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        name: black

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
    -   id: mypy

