dependencies:
    # - <organization(github account)/repo>@<version>
    - OpenZeppelin/openzeppelin-contracts@4.5.0
    - smartcontractkit/chainlink-brownie-contracts@0.4.0
compiler:
    solc:
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
            - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"
dotenv: .env
networks:
    default: development
    development:
        gas_price: 17000000000
    hardhat:
        gas_price: 17000000000
        truhuis: ${ACCOUNT_HARDHAT_0}
        state_government_nld_account: ${ACCOUNT_HARDHAT_1}
        state_government_usa_account: ${ACCOUNT_HARDHAT_2}
        citizen_nld_1: ${ACCOUNT_HARDHAT_3}
        citizen_nld_2: ${ACCOUNT_HARDHAT_4}
        citizen_nld_3: ${ACCOUNT_HARDHAT_5}
        citizen_usa_1: ${ACCOUNT_HARDHAT_6}
        citizen_usa_2: ${ACCOUNT_HARDHAT_7}
        citizen_usa_3: ${ACCOUNT_HARDHAT_8}
        chainlink_keeper: ${ACCOUNT_HARDHAT_19}
    mainnet:
        verify: False
    rinkeby:
        verify: False
    kovan:
        verify: True
        truhuis: ${ACCOUNT_TEST_0}
        state_government_nld: ${ACCOUNT_TEST_1}
        state_government_usa: ${ACCOUNT_TEST_2}
        citizen_nld_1: ${ACCOUNT_TEST_3}
        citizen_nld_2: ${ACCOUNT_TEST_4}
        citizen_nld_3: ${ACCOUNT_TEST_5}
        citizen_usa_1: ${ACCOUNT_TEST_6}
        citizen_usa_2: ${ACCOUNT_TEST_7}
        citizen_usa_3: ${ACCOUNT_TEST_8}
        chainlink_keeper: ${ACCOUNT_TEST_9}
    polygon:
        verify: False
wallets:
    rinkeby: ${PRIVATE_KEY_TEST_0}
    kovan:
        truhuis: ${PRIVATE_KEY_TEST_0}
        state_government_nld: ${PRIVATE_KEY_TEST_1}
        state_government_usa: ${PRIVATE_KEY_TEST_2}
        citizen_nld_1: ${PRIVATE_KEY_TEST_3}
        citizen_nld_2: ${PRIVATE_KEY_TEST_4}
        citizen_nld_3: ${PRIVATE_KEY_TEST_5}
        citizen_usa_1: ${PRIVATE_KEY_TEST_6} 
        citizen_usa_2: ${PRIVATE_KEY_TEST_7}
        citizen_usa_3: ${PRIVATE_KEY_TEST_8}
        chainlink_keeper: ${PRIVATE_KEY_TEST_9}
    hardhat:
        truhuis: ${PRIVATE_KEY_HARDHAT_0}
        state_government_nld: ${PRIVATE_KEY_HARDHAT_1}
        state_government_usa: ${PRIVATE_KEY_HARDHAT_2}
        citizen_nld_1: ${PRIVATE_KEY_HARDHAT_3}
        citizen_nld_2: ${PRIVATE_KEY_HARDHAT_4}
        citizen_nld_3: ${PRIVATE_KEY_HARDHAT_5}
        citizen_usa_1: ${PRIVATE_KEY_HARDHAT_6}
        citizen_usa_2: ${PRIVATE_KEY_HARDHAT_7}
        citizen_usa_3: ${PRIVATE_KEY_HARDHAT_8}
        chainlink_keeper: ${PRIVATE_KEY_HARDHAT_19}
