[tool.black]
line-length = 80

[tool.pyright]
pythonVersion = '3.9.9'
reportMissingImports = true
reportMissingTypeStubs = false
disableOrganizeImports = true
pythonPlatform = 'Darwin'
typeCheckingMode = 'basic'
